name: CI for Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies for Backend
      run: |
        cd backend
        npm install

    - name: Install dependencies for Frontend
      run: |
        cd frontend
        npm install

    - name: Run Backend Unit Tests
      run: |
        cd backend
        npm test

    - name: Run Frontend Unit Tests
      run: |
        cd frontend
        npm test

    - name: Merge dev into main
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin main
        git checkout main
        git merge dev
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
