name: CI/CD for Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  build-and-test-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies for Backend
      run: |
        cd backend
        npm install

    - name: Install dependencies for Frontend
      run: |
        cd frontend
        npm install

    - name: Run Backend Unit Tests
      run: |
        cd backend
        npm test

    - name: Run Frontend Unit Tests
      run: |
        cd frontend
        npm test

    - name: Merge dev into main
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin main
        git checkout main
        git merge dev --allow-unrelated-histories -X theirs --no-edit
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# This is a new step to trigger the main.yml workflow
    - name: Trigger Main Branch Workflow
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
          -d '{"ref":"main"}'
