name: CI/CD for dev branch

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies for Backend
      - name: Install dependencies for Backend
        run: |
          cd backend
          npm install

      # 4. Install dependencies for Frontend
      - name: Install dependencies for Frontend
        run: |
          cd frontend
          npm install

      # 5. Run Backend Unit Tests
      - name: Run Backend Unit Tests
        run: |
          cd backend
          npm test

      # 6. Run Frontend Unit Tests
      - name: Run Frontend Unit Tests
        run: |
          cd frontend
          npm test

      # 7. Merge dev into main
      - name: Merge dev into main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main
          git merge dev --no-ff -m "CI/CD: Merging dev into main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
